language: rust
sudo: required
rust:
  - 1.8.0
  - stable
  - nightly
services:
  - docker
script:
  - if [[ $TRAVIS_RUST_VERSION = nightly* ]]; then
      sh ci/run-travis.sh;
    else
      cargo test;
    fi
env:
  matrix:
    - ARCH=x86_64
    - ARCH=i686
os:
  - linux
  - osx
matrix:
  include:
    - os: linux
      env: TARGET=arm-linux-androideabi
      rust: nightly
    - os: linux
      env: TARGET=x86_64-unknown-linux-musl
      rust: nightly
    - os: linux
      env: TARGET=arm-unknown-linux-gnueabihf
      rust: nightly
    - os: linux
      env: TARGET=mips-unknown-linux-gnu
      rust: nightly
    - os: linux
      env: TARGET=aarch64-unknown-linux-gnu
      rust: nightly
    - os: osx
      env: TARGET=i386-apple-ios
      rust: nightly-2015-09-08
    - os: osx
      env: TARGET=x86_64-apple-ios
      rust: nightly-2015-09-08
  allow_failures:
    # Not sure what's going on here
    - env: TARGET=i386-apple-ios
    - env: TARGET=x86_64-apple-ios
    # QEMU is extremely flaky
    - env: TARGET=aarch64-unknown-linux-gnu
    - env: TARGET=arm-unknown-linux-gnueabihf
    - env: TARGET=mips-unknown-linux-gnu
    # Remove once libc#d7d4f is published
    - env: TARGET=arm-linux-androideabi
    # Breaking on the new travis GCE infrastructure?
    - env: TARGET=x86_64-unknown-linux-musl
notifications:
  email:
    on_success: never
