[package]
name = "mmap"
version = "0.0.1"
authors = ["Dan Burkert <dan@danburkert.com>"]

[dependencies]
bitflags = "*"
libc = "*"

[dev-dependencies]
tempdir = "*"

[target.x86_64-pc-windows-gnu.dependencies.kernel32-sys]
git = "https://github.com/danburkert/winapi-rs.git"
path = "lib/kernel32-sys"

[target.i686-pc-windows-gnu.dependencies.kernel32-sys]
git = "https://github.com/danburkert/winapi-rs.git"
path = "lib/kernel32-sys"
