[package]
name = "mmap"
version = "0.0.1"
authors = ["Dan Burkert <dan@danburkert.com>"]

[dependencies]
bitflags = "*"
libc = "*"

[dependencies.kernel32-sys]
git = "https://github.com/retep998/winapi-rs.git"
path = "lib/kernel32-sys"

[dev-dependencies]
tempdir = "*"
